name: Version on Main Push

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: write
  pull-requests: write
  statuses: read

jobs:
  update-version:
    uses: ./.github/workflows/update_version_workflow.yml
    with:
      allowed_branches: main
